name: RSS - Substack - SERP AI

on:
  workflow_dispatch:
  push:
    paths:
      - 'substack/serpai/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate RSS Feed
      run: python ./scripts/generate_rss.py --source content/substack/serpai --output content/substack/serpai/feed.xml

    - name: Commit and Push RSS Feed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add content/substack/serpai/feed.xml
        git commit -m "Update Substack RSS Feed for SERP AI"
        git push
