name: RSS Generation

on:
  workflow_dispatch:
  push:
    paths:
      - 'content/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Up Git
      run: |
        git config --local user.email "serpa-actions@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git pull origin main

    - name: Generate RSS Feed
      run: python ./scripts/generate_rss.py 

    - name: Commit Generated RSS
      run: |
        git add ./rss/*
        git status
        git commit -m "Update RSS feeds"
        git push